name: ci
on: push

env:
  MYSQL_ROOT_PASSWORD: password
  DB_NAME: test
  DB_USER: root
  DB_PASS: toor

jobs:
  run_code_checks:
    runs-on: ubuntu-latest
    steps:
      - name: setup database
        run: |
          # sudo apt-get update -y
          sudo /etc/init.d/mysql start
          sudo systemctl status mysql.service
          sudo mysql -e 'ALTER USER "${{env.DB_USER}}"@"localhost" IDENTIFIED BY "${{env.DB_PASS}}";' -u${{env.DB_USER}} -p ${{env.MYSQL_ROOT_PASSWORD}}
          sudo mysql -e 'CREATE DATABASE ${{env.DB_NAME}};' -u ${{env.DB_USER}} -p ${{env.DB_PASS}}
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20
      - name: linting
        run: |
          go fmt ./...
          go vet ./...
      - name: test
        run: go test
